export const FlashStore = (state:any) => state.flash
export const UserStore = (state:any) => state.user
export const AlbumsStore = (state:any) => state.albums
export const AlbumStore = (state:any) => state.album
export const CartStore = (state:any) => state.cart
export const TransactionStore = (state:any) => state.transaction
export const TransactionsStore = (state:any) => state.transactions
export const ReviewStore = (state:any) => state.review
export const BlogStore = (state:any) => state.blog
export const BlogsStore = (state:any) => state.blogs
export const CustomersStore = (state:any) => state.customers
export const EmployeesStore = (state:any) => state.employees
export const ArtistsStore = (state:any) => state.artists
export const ReviewsStore = (state:any) => state.artists
